// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessType.proto

#ifndef PROTOBUF_MessType_2eproto__INCLUDED
#define PROTOBUF_MessType_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ssp {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessType_2eproto();
void protobuf_AssignDesc_MessType_2eproto();
void protobuf_ShutdownFile_MessType_2eproto();

class RegReq;
class RegRep;

// ===================================================================

class RegReq : public ::google::protobuf::Message {
 public:
  RegReq();
  virtual ~RegReq();

  RegReq(const RegReq& from);

  inline RegReq& operator=(const RegReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegReq& default_instance();

  void Swap(RegReq* other);

  // implements Message ----------------------------------------------

  RegReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegReq& from);
  void MergeFrom(const RegReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 verion = 1;
  inline bool has_verion() const;
  inline void clear_verion();
  static const int kVerionFieldNumber = 1;
  inline ::google::protobuf::int32 verion() const;
  inline void set_verion(::google::protobuf::int32 value);

  // optional int32 mess_type = 2;
  inline bool has_mess_type() const;
  inline void clear_mess_type();
  static const int kMessTypeFieldNumber = 2;
  inline ::google::protobuf::int32 mess_type() const;
  inline void set_mess_type(::google::protobuf::int32 value);

  // optional string user_name = 3;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 3;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // optional string password = 4;
  inline bool has_password() const;
  inline void clear_password();
  static const int kPasswordFieldNumber = 4;
  inline const ::std::string& password() const;
  inline void set_password(const ::std::string& value);
  inline void set_password(const char* value);
  inline void set_password(const char* value, size_t size);
  inline ::std::string* mutable_password();
  inline ::std::string* release_password();
  inline void set_allocated_password(::std::string* password);

  // optional int32 from = 5;
  inline bool has_from() const;
  inline void clear_from();
  static const int kFromFieldNumber = 5;
  inline ::google::protobuf::int32 from() const;
  inline void set_from(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ssp.RegReq)
 private:
  inline void set_has_verion();
  inline void clear_has_verion();
  inline void set_has_mess_type();
  inline void clear_has_mess_type();
  inline void set_has_user_name();
  inline void clear_has_user_name();
  inline void set_has_password();
  inline void clear_has_password();
  inline void set_has_from();
  inline void clear_has_from();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 verion_;
  ::google::protobuf::int32 mess_type_;
  ::std::string* user_name_;
  ::std::string* password_;
  ::google::protobuf::int32 from_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_MessType_2eproto();
  friend void protobuf_AssignDesc_MessType_2eproto();
  friend void protobuf_ShutdownFile_MessType_2eproto();

  void InitAsDefaultInstance();
  static RegReq* default_instance_;
};
// -------------------------------------------------------------------

class RegRep : public ::google::protobuf::Message {
 public:
  RegRep();
  virtual ~RegRep();

  RegRep(const RegRep& from);

  inline RegRep& operator=(const RegRep& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RegRep& default_instance();

  void Swap(RegRep* other);

  // implements Message ----------------------------------------------

  RegRep* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegRep& from);
  void MergeFrom(const RegRep& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 verion = 1;
  inline bool has_verion() const;
  inline void clear_verion();
  static const int kVerionFieldNumber = 1;
  inline ::google::protobuf::int32 verion() const;
  inline void set_verion(::google::protobuf::int32 value);

  // optional int32 mess_type = 2;
  inline bool has_mess_type() const;
  inline void clear_mess_type();
  static const int kMessTypeFieldNumber = 2;
  inline ::google::protobuf::int32 mess_type() const;
  inline void set_mess_type(::google::protobuf::int32 value);

  // optional int32 ret = 3;
  inline bool has_ret() const;
  inline void clear_ret();
  static const int kRetFieldNumber = 3;
  inline ::google::protobuf::int32 ret() const;
  inline void set_ret(::google::protobuf::int32 value);

  // optional int32 user_id = 4;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 4;
  inline ::google::protobuf::int32 user_id() const;
  inline void set_user_id(::google::protobuf::int32 value);

  // optional string user_name = 5;
  inline bool has_user_name() const;
  inline void clear_user_name();
  static const int kUserNameFieldNumber = 5;
  inline const ::std::string& user_name() const;
  inline void set_user_name(const ::std::string& value);
  inline void set_user_name(const char* value);
  inline void set_user_name(const char* value, size_t size);
  inline ::std::string* mutable_user_name();
  inline ::std::string* release_user_name();
  inline void set_allocated_user_name(::std::string* user_name);

  // @@protoc_insertion_point(class_scope:ssp.RegRep)
 private:
  inline void set_has_verion();
  inline void clear_has_verion();
  inline void set_has_mess_type();
  inline void clear_has_mess_type();
  inline void set_has_ret();
  inline void clear_has_ret();
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_user_name();
  inline void clear_has_user_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 verion_;
  ::google::protobuf::int32 mess_type_;
  ::google::protobuf::int32 ret_;
  ::google::protobuf::int32 user_id_;
  ::std::string* user_name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_MessType_2eproto();
  friend void protobuf_AssignDesc_MessType_2eproto();
  friend void protobuf_ShutdownFile_MessType_2eproto();

  void InitAsDefaultInstance();
  static RegRep* default_instance_;
};
// ===================================================================


// ===================================================================

// RegReq

// optional int32 verion = 1;
inline bool RegReq::has_verion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegReq::set_has_verion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegReq::clear_has_verion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegReq::clear_verion() {
  verion_ = 0;
  clear_has_verion();
}
inline ::google::protobuf::int32 RegReq::verion() const {
  return verion_;
}
inline void RegReq::set_verion(::google::protobuf::int32 value) {
  set_has_verion();
  verion_ = value;
}

// optional int32 mess_type = 2;
inline bool RegReq::has_mess_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegReq::set_has_mess_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegReq::clear_has_mess_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegReq::clear_mess_type() {
  mess_type_ = 0;
  clear_has_mess_type();
}
inline ::google::protobuf::int32 RegReq::mess_type() const {
  return mess_type_;
}
inline void RegReq::set_mess_type(::google::protobuf::int32 value) {
  set_has_mess_type();
  mess_type_ = value;
}

// optional string user_name = 3;
inline bool RegReq::has_user_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegReq::set_has_user_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegReq::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegReq::clear_user_name() {
  if (user_name_ != &::google::protobuf::internal::kEmptyString) {
    user_name_->clear();
  }
  clear_has_user_name();
}
inline const ::std::string& RegReq::user_name() const {
  return *user_name_;
}
inline void RegReq::set_user_name(const ::std::string& value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
}
inline void RegReq::set_user_name(const char* value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
}
inline void RegReq::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegReq::mutable_user_name() {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  return user_name_;
}
inline ::std::string* RegReq::release_user_name() {
  clear_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = user_name_;
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RegReq::set_allocated_user_name(::std::string* user_name) {
  if (user_name_ != &::google::protobuf::internal::kEmptyString) {
    delete user_name_;
  }
  if (user_name) {
    set_has_user_name();
    user_name_ = user_name;
  } else {
    clear_has_user_name();
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string password = 4;
inline bool RegReq::has_password() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegReq::set_has_password() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegReq::clear_has_password() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegReq::clear_password() {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    password_->clear();
  }
  clear_has_password();
}
inline const ::std::string& RegReq::password() const {
  return *password_;
}
inline void RegReq::set_password(const ::std::string& value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void RegReq::set_password(const char* value) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(value);
}
inline void RegReq::set_password(const char* value, size_t size) {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  password_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegReq::mutable_password() {
  set_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    password_ = new ::std::string;
  }
  return password_;
}
inline ::std::string* RegReq::release_password() {
  clear_has_password();
  if (password_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = password_;
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RegReq::set_allocated_password(::std::string* password) {
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (password) {
    set_has_password();
    password_ = password;
  } else {
    clear_has_password();
    password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 from = 5;
inline bool RegReq::has_from() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegReq::set_has_from() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegReq::clear_has_from() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegReq::clear_from() {
  from_ = 0;
  clear_has_from();
}
inline ::google::protobuf::int32 RegReq::from() const {
  return from_;
}
inline void RegReq::set_from(::google::protobuf::int32 value) {
  set_has_from();
  from_ = value;
}

// -------------------------------------------------------------------

// RegRep

// optional int32 verion = 1;
inline bool RegRep::has_verion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegRep::set_has_verion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegRep::clear_has_verion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegRep::clear_verion() {
  verion_ = 0;
  clear_has_verion();
}
inline ::google::protobuf::int32 RegRep::verion() const {
  return verion_;
}
inline void RegRep::set_verion(::google::protobuf::int32 value) {
  set_has_verion();
  verion_ = value;
}

// optional int32 mess_type = 2;
inline bool RegRep::has_mess_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegRep::set_has_mess_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegRep::clear_has_mess_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegRep::clear_mess_type() {
  mess_type_ = 0;
  clear_has_mess_type();
}
inline ::google::protobuf::int32 RegRep::mess_type() const {
  return mess_type_;
}
inline void RegRep::set_mess_type(::google::protobuf::int32 value) {
  set_has_mess_type();
  mess_type_ = value;
}

// optional int32 ret = 3;
inline bool RegRep::has_ret() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegRep::set_has_ret() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegRep::clear_has_ret() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegRep::clear_ret() {
  ret_ = 0;
  clear_has_ret();
}
inline ::google::protobuf::int32 RegRep::ret() const {
  return ret_;
}
inline void RegRep::set_ret(::google::protobuf::int32 value) {
  set_has_ret();
  ret_ = value;
}

// optional int32 user_id = 4;
inline bool RegRep::has_user_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegRep::set_has_user_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegRep::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegRep::clear_user_id() {
  user_id_ = 0;
  clear_has_user_id();
}
inline ::google::protobuf::int32 RegRep::user_id() const {
  return user_id_;
}
inline void RegRep::set_user_id(::google::protobuf::int32 value) {
  set_has_user_id();
  user_id_ = value;
}

// optional string user_name = 5;
inline bool RegRep::has_user_name() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegRep::set_has_user_name() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegRep::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegRep::clear_user_name() {
  if (user_name_ != &::google::protobuf::internal::kEmptyString) {
    user_name_->clear();
  }
  clear_has_user_name();
}
inline const ::std::string& RegRep::user_name() const {
  return *user_name_;
}
inline void RegRep::set_user_name(const ::std::string& value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
}
inline void RegRep::set_user_name(const char* value) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(value);
}
inline void RegRep::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  user_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegRep::mutable_user_name() {
  set_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    user_name_ = new ::std::string;
  }
  return user_name_;
}
inline ::std::string* RegRep::release_user_name() {
  clear_has_user_name();
  if (user_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = user_name_;
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RegRep::set_allocated_user_name(::std::string* user_name) {
  if (user_name_ != &::google::protobuf::internal::kEmptyString) {
    delete user_name_;
  }
  if (user_name) {
    set_has_user_name();
    user_name_ = user_name;
  } else {
    clear_has_user_name();
    user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ssp

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessType_2eproto__INCLUDED
