// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RelationInfo.proto

#ifndef PROTOBUF_RelationInfo_2eproto__INCLUDED
#define PROTOBUF_RelationInfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ssp {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RelationInfo_2eproto();
void protobuf_AssignDesc_RelationInfo_2eproto();
void protobuf_ShutdownFile_RelationInfo_2eproto();

class RelationInfo;

// ===================================================================

class RelationInfo : public ::google::protobuf::Message {
 public:
  RelationInfo();
  virtual ~RelationInfo();

  RelationInfo(const RelationInfo& from);

  inline RelationInfo& operator=(const RelationInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RelationInfo& default_instance();

  void Swap(RelationInfo* other);

  // implements Message ----------------------------------------------

  RelationInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RelationInfo& from);
  void MergeFrom(const RelationInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 verion = 1;
  inline bool has_verion() const;
  inline void clear_verion();
  static const int kVerionFieldNumber = 1;
  inline ::google::protobuf::int32 verion() const;
  inline void set_verion(::google::protobuf::int32 value);

  // optional int32 user_id = 2;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  inline ::google::protobuf::int32 user_id() const;
  inline void set_user_id(::google::protobuf::int32 value);

  // repeated int32 friend_user_id = 3;
  inline int friend_user_id_size() const;
  inline void clear_friend_user_id();
  static const int kFriendUserIdFieldNumber = 3;
  inline ::google::protobuf::int32 friend_user_id(int index) const;
  inline void set_friend_user_id(int index, ::google::protobuf::int32 value);
  inline void add_friend_user_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      friend_user_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_friend_user_id();

  // repeated int32 black_user_id = 4;
  inline int black_user_id_size() const;
  inline void clear_black_user_id();
  static const int kBlackUserIdFieldNumber = 4;
  inline ::google::protobuf::int32 black_user_id(int index) const;
  inline void set_black_user_id(int index, ::google::protobuf::int32 value);
  inline void add_black_user_id(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      black_user_id() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_black_user_id();

  // @@protoc_insertion_point(class_scope:ssp.RelationInfo)
 private:
  inline void set_has_verion();
  inline void clear_has_verion();
  inline void set_has_user_id();
  inline void clear_has_user_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 verion_;
  ::google::protobuf::int32 user_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > friend_user_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > black_user_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_RelationInfo_2eproto();
  friend void protobuf_AssignDesc_RelationInfo_2eproto();
  friend void protobuf_ShutdownFile_RelationInfo_2eproto();

  void InitAsDefaultInstance();
  static RelationInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// RelationInfo

// optional int32 verion = 1;
inline bool RelationInfo::has_verion() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RelationInfo::set_has_verion() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RelationInfo::clear_has_verion() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RelationInfo::clear_verion() {
  verion_ = 0;
  clear_has_verion();
}
inline ::google::protobuf::int32 RelationInfo::verion() const {
  return verion_;
}
inline void RelationInfo::set_verion(::google::protobuf::int32 value) {
  set_has_verion();
  verion_ = value;
}

// optional int32 user_id = 2;
inline bool RelationInfo::has_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RelationInfo::set_has_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RelationInfo::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RelationInfo::clear_user_id() {
  user_id_ = 0;
  clear_has_user_id();
}
inline ::google::protobuf::int32 RelationInfo::user_id() const {
  return user_id_;
}
inline void RelationInfo::set_user_id(::google::protobuf::int32 value) {
  set_has_user_id();
  user_id_ = value;
}

// repeated int32 friend_user_id = 3;
inline int RelationInfo::friend_user_id_size() const {
  return friend_user_id_.size();
}
inline void RelationInfo::clear_friend_user_id() {
  friend_user_id_.Clear();
}
inline ::google::protobuf::int32 RelationInfo::friend_user_id(int index) const {
  return friend_user_id_.Get(index);
}
inline void RelationInfo::set_friend_user_id(int index, ::google::protobuf::int32 value) {
  friend_user_id_.Set(index, value);
}
inline void RelationInfo::add_friend_user_id(::google::protobuf::int32 value) {
  friend_user_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RelationInfo::friend_user_id() const {
  return friend_user_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RelationInfo::mutable_friend_user_id() {
  return &friend_user_id_;
}

// repeated int32 black_user_id = 4;
inline int RelationInfo::black_user_id_size() const {
  return black_user_id_.size();
}
inline void RelationInfo::clear_black_user_id() {
  black_user_id_.Clear();
}
inline ::google::protobuf::int32 RelationInfo::black_user_id(int index) const {
  return black_user_id_.Get(index);
}
inline void RelationInfo::set_black_user_id(int index, ::google::protobuf::int32 value) {
  black_user_id_.Set(index, value);
}
inline void RelationInfo::add_black_user_id(::google::protobuf::int32 value) {
  black_user_id_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
RelationInfo::black_user_id() const {
  return black_user_id_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
RelationInfo::mutable_black_user_id() {
  return &black_user_id_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ssp

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RelationInfo_2eproto__INCLUDED
